### ISSUE TITLE
is there supposed to be support for tables?

### ISSUE THREAD

**Issue by shriram** [greghendershott/markdown#86] opened 2020-09-08 21:48 UTC
GitHub-flavored Markdown has support for tables, which is awfully nice. Is there supposed to be support in this package? (I haven't gotten it to work, but maybe that's not surprising!)

**Comment by sorawee** [comment] 2020-09-08 23:33
See also https://github.com/greghendershott/markdown/pull/56. You could try to download the PR branch and see if it works for you.

**Comment by greghendershott** [comment] 2020-09-10 13:06
As @sorawee mentioned this is an open enhancement, so I'll close this issue as a dupe of #72, but please feel free to comment more there.

**Closed by greghendershott** 2020-09-10 13:06 UTC
Labels: duplicate
